### ISSUE TITLE
The performance of default voc8.res50v3+.CPS

### ISSUE THREAD

**Issue by yangkai798** [charlesCXK/TorchSemiSeg#35] opened 2021-09-26 06:51 UTC
thank you for release the code. we run the default config as your public in voc8.res50v3+.CPS, the best performance is 72.76, a little lower than the 73.20 in paper. have any other tricks?  the default epoch is 34, the paper is 60? but your released log, 73.28 is also use 34 epoch.

**Comment by charlesCXK** [comment] 2021-09-27 05:04
Hi, we train this model for 34 epochs **with no additional tricks**. Please try to use the Docker we provide to run these experiments (https://github.com/charlesCXK/TorchSemiSeg/issues/27).

**Comment by yangkai798** [comment] 2021-09-27 08:12
thank you. But I have installed with conda env as the doc. the version is same. have any other random factor?  I have no permission to use nvidia-docker in cluster. the code and config is same between docker and this repo?

**Comment by yangkai798** [comment] 2021-09-28 03:52
thanks , its OK. I run it again,  the performance is 73.32.

**Comment by charlesCXK** [comment] 2021-09-28 04:21
The docker only provides the environment to run the experiments and no code is stored in it. Since you have reproduced the result, I will close this issue. Welcome to re-open it if you have any questions.

**Closed by charlesCXK** 2021-09-28 04:21 UTC
